In [1]:
import os
import pandas as pd
import numpy as np

In [2]:
ocr_filenames = set()
for name in os.listdir("Bill.com/ocr/"):
    if name.endswith(".csv"):
        ocr_filenames.add(name)

In [3]:
ocr_columns = ["x1","y1","x2","y2","x3","y3","x4","y4","TEXT"]
ocr_parsed = {}
for filename in ocr_filenames:
    cur_ocr = [[] for i in range(9)]
    with open(f"Bill.com/ocr/{filename}") as csv_file:
        for line in csv_file:
            for idx, num in enumerate(line[:-1].split(',', 8)):
                cur_ocr[idx].append(num)

    for i in range(8):
        cur_ocr[i] = np.asarray(cur_ocr[i], dtype=float)

    df = pd.DataFrame(data={col: cur_data_col for col, cur_data_col in zip(ocr_columns, cur_ocr)})
    ocr_parsed[filename[:-4]] = df

In [4]:
ocr_parsed["00d0950145735"]

,x1,y1,x2,y2,x3,y3,x4,y4,TEXT
0,104.0,392.0,815.0,392.0,815.0,428.0,104.0,428.0,ONE ONE THREE SEAFOOD RESTAURANT SDN BHD
1,353.0,433.0,547.0,433.0,547.0,473.0,353.0,473.0,(1120908-M)
2,107.0,479.0,820.0,479.0,820.0,514.0,107.0,514.0,"NO.1, TAMAN SRI DENGKIL, JALAN AIR HITAM"
3,248.0,523.0,670.0,523.0,670.0,561.0,248.0,561.0,"43800 DENGKIL, SELANGOR."
4,212.0,566.0,707.0,566.0,707.0,606.0,212.0,606.0,GST REG. NO : 000670224384)
5,248.0,611.0,634.0,611.0,634.0,649.0,248.0,649.0,TAX INVOICE
6,109.0,654.0,385.0,654.0,385.0,691.0,109.0,691.0,TABLE 37
7,139.0,694.0,446.0,694.0,446.0,733.0,139.0,733.0,BILL#:V001-539829
8,528.0,697.0,778.0,697.0,778.0,735.0,528.0,735.0,ORDER#: 139931
9,105.0,741.0,180.0,741.0,180.0,777.0,105.0,777.0,DATE
10,232.0,741.0,602.0,741.0,602.0,782.0,232.0,782.0,: 05-06-2018 20:23:14
11,105.0,785.0,463.0,785.0,463.0,821.0,105.0,821.0,CASHIER: 113 CASHIER
12,619.0,780.0,745.0,780.0,745.0,823.0,619.0,823.0,PAX(S):
13,791.0,784.0,816.0,784.0,816.0,825.0,791.0,825.0,0
14,105.0,872.0,162.0,872.0,162.0,915.0,105.0,915.0,QTY
15,211.0,871.0,410.0,871.0,410.0,914.0,211.0,914.0,DESCRIPTION
16,653.0,873.0,814.0,873.0,814.0,912.0,653.0,912.0,TOTAL TAX
17,162.0,964.0,176.0,964.0,176.0,999.0,162.0,999.0,1
18,565.0,963.0,587.0,963.0,587.0,998.0,565.0,998.0,D
19,621.0,962.0,764.0,962.0,764.0,1000.0,621.0,1000.0,15.00 SR
20,105.0,1003.0,340.0,1003.0,340.0,1042.0,105.0,1042.0,OMELLETE ITEM
21,159.0,1048.0,181.0,1048.0,181.0,1084.0,159.0,1084.0,1
22,565.0,1051.0,586.0,1051.0,586.0,1087.0,565.0,1087.0,D
23,621.0,1050.0,764.0,1050.0,764.0,1089.0,621.0,1089.0,10.00 SR
24,105.0,1093.0,337.0,1093.0,337.0,1132.0,105.0,1132.0,VEGE ITEM (S)
25,165.0,1136.0,180.0,1136.0,180.0,1172.0,165.0,1172.0,1
26,563.0,1138.0,587.0,1138.0,587.0,1176.0,563.0,1176.0,D
27,618.0,1138.0,763.0,1138.0,763.0,1174.0,618.0,1174.0,22.00 SR
28,103.0,1177.0,673.0,1177.0,673.0,1219.0,103.0,1219.0,RICE W SEAFOOD /MEAT ITEM SINGLE
29,162.0,1226.0,180.0,1226.0,180.0,1257.0,162.0,1257.0,1
30,566.0,1224.0,587.0,1224.0,587.0,1260.0,566.0,1260.0,D
31,636.0,1223.0,763.0,1223.0,763.0,1259.0,636.0,1259.0,5.00 SR
32,106.0,1266.0,249.0,1266.0,249.0,1307.0,106.0,1307.0,BEVERAGE
33,103.0,1353.0,494.0,1353.0,494.0,1396.0,103.0,1396.0,TOTAL (EXCLUDING GST):
34,725.0,1356.0,816.0,1356.0,816.0,1392.0,725.0,1392.0,52.00
35,102.0,1395.0,545.0,1395.0,545.0,1439.0,102.0,1439.0,TOTAL (INCLUSIVE OF GST):
36,724.0,1399.0,816.0,1399.0,816.0,1434.0,724.0,1434.0,52.00
37,108.0,1438.0,309.0,1438.0,309.0,1480.0,108.0,1480.0,TOTAL :
38,636.0,1442.0,811.0,1442.0,811.0,1478.0,636.0,1478.0,52.00
39,103.0,1528.0,262.0,1528.0,262.0,1562.0,103.0,1562.0,CLOSED: 1
40,442.0,1529.0,622.0,1529.0,622.0,1565.0,442.0,1565.0,05-06-2018
41,669.0,1529.0,816.0,1529.0,816.0,1568.0,669.0,1568.0,20:56:06
42,105.0,1572.0,445.0,1572.0,445.0,1608.0,105.0,1608.0,SERVER: 113 CASHIER
43,103.0,1614.0,211.0,1614.0,211.0,1650.0,103.0,1650.0,CASH :
44,724.0,1616.0,815.0,1616.0,815.0,1655.0,724.0,1655.0,52.00
45,103.0,1701.0,303.0,1701.0,303.0,1744.0,103.0,1744.0,GST SUMMARY
46,458.0,1704.0,634.0,1704.0,634.0,1745.0,458.0,1745.0,AMOUNT(RM)
47,688.0,1704.0,814.0,1704.0,814.0,1745.0,688.0,1745.0,TAX(RM)
48,106.0,1747.0,144.0,1747.0,144.0,1785.0,106.0,1785.0,SR
49,284.0,1744.0,386.0,1744.0,386.0,1787.0,284.0,1787.0,(@ 0%)
50,546.0,1747.0,638.0,1747.0,638.0,1783.0,546.0,1783.0,52.00
51,742.0,1750.0,816.0,1750.0,816.0,1786.0,742.0,1786.0,0.00
52,282.0,1874.0,620.0,1874.0,620.0,1913.0,282.0,1913.0,**** THANK YOU ****
53,316.0,1918.0,622.0,1918.0,622.0,1964.0,316.0,1964.0,PLEASE COME AGAIN